# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "A technical blog"
description: > # this means to ignore newlines until "email:"
   

email: goran.subotic@gmail.com
#blog logo
logo: "https://www.gravatar.com/avatar/e0eb4387daa920300f1304ac7a6a3094?s=500&d=identicon"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

authors:
  goran:
    name: 'Goran Subotic'
    author: 'Goran Subotic'
    author_image: "https://www.gravatar.com/avatar/e0eb4387daa920300f1304ac7a6a3094?s=500&d=identicon"
  savo:
    name: 'Savo Garovic'
    author: 'Savo Garovic'
    author_image: "https://www.gravatar.com/avatar/e0eb4387daa920300f1304ac7a6a3094?s=500"

# authors:
#   hanzou:
#     name: Hanzou Hattori
#     display_name: Hanzou
#     gravatar: c66919cb194f96c696c1da0c47354a6a
#     email: hanzou@company.com

paginate:	5

url: "/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/__goran
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/goran-subotic
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
